### ISSUE TITLE
emailSettings for SMTP

### ISSUE THREAD

**Issue by johblau** [zemirco/lockit-sendmail#4]
Hi zemirco,
when I send signup notification email, lockit-sendmail (or in my case node-smtp-transport) always tries to connect to localhost without user credentials.
My settings:

```
    emailType: 'nodemailer-smtp-transport',
    emailFrom : '....',

    emailSettings: {
        host: '............',
        port: 25,
        secure:false,
        auth: {
            user: '......',
            pass: '....'

        },
....
```

I can't find the code in your modules, where the emailSettings is used or copied for nodemailer configuration.

Thx for help
Johann

**Comment by brualves** [comment]
Hi there,
I'm facing the same issue...

**Comment by shawnbissell** [comment]
just ran into same issue ... line 58 should be changed from

var transporter = nodemailer.createTransport(that.transport(options));
to 
var transporter = nodemailer.createTransport(that.transport(config.emailSettings));

**Comment by zemirco** [comment]
Should be fixed with https://github.com/zemirco/lockit-sendmail/pull/6 now.
