### ISSUE TITLE
Please merge pull request #6

### ISSUE THREAD

**Issue by shawnbissell** [zemirco/lockit-sendmail#8]
The email config setting have been broken since September 2014, other people have created many forks to work around this issue.
https://github.com/zemirco/lockit-sendmail/pull/6

**Comment by zemirco** [comment]
Currently having some time to work on Lockit again :) . Merged PR - https://github.com/zemirco/lockit-sendmail/commit/fd99248b132aca89deb707bf5b49821eef9912ac
